# Generated by Django 5.2.2 on 2026-01-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
