# Generated by Django 5.2.2 on 2026-01-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
