# Generated by Django 5.2.2 on 2025-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
