# Generated by Django 5.2.2 on 2026-02-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='indistry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
