# Generated by Django 5.2.2 on 2026-02-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_company_indistry_company_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='indistry',
            new_name='industry',
        ),
    ]
