# Generated by Django 5.2.2 on 2026-02-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_company_created_at_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
