# Generated by Django 5.2.2 on 2026-03-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='instructor_notified',
            field=models.BooleanField(default=False),
        ),
    ]
